version: '3.8'

services:
  producer:
    build: ./producer
    env_file:
      - ./producer/.env
    networks:
      - backend

  consumer:
    build: ./consumer
    networks:
      - backend
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appdb
    networks:
      - backend
    ports:
      - '3306:3306'

  nginx:
    image: nginx:alpine
    ports:
      - '443:443'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    depends_on:
      - producer
    networks:
      - backend

networks:
  backend:
